# github.com/Dmitrii-Khramtsov/orderservice/config.yml
cache:
  capacity: 10000
  get_all_limit: 1000
  restoration:
    timeout: 5m
    batch_size: 1000

database:
  max_open_conns: 50
  max_idle_conns: 25
  conn_max_lifetime: 30m
  statement_timeout: 30s
  idle_in_tx_session_timeout: 10s

kafka:
  brokers:
    - "kafka1:9092"
    - "kafka2:9092"
  topic: "orders"
  group_id: "orderservice"
  dlq_topic: "orders-dlq"
  max_retries: 5
  processing_time: 60s
  min_bytes: 10000
  max_bytes: 10000000
  max_wait: 1s
  commit_interval: 1s
  batch_timeout: 100ms
  batch_size: 1
  retry:
    initial_interval: 1s
    multiplier: 2
    max_interval: 30s
    max_elapsed_time: 5m
    randomization_factor: 0.5

server:
  port: "8081"

migrations:
  migrations_path: "/app/internal/infrastructure/database/migrations"